jobs:
  test:
    name: Strong CI by multiply java versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Run integration test
      run: scripts/integration-test.sh
    - continue-on-error: true
      name: Remove self maven install files
      run: rm -rf $HOME/.m2/repository/com/alibaba/{transmittable-thread-local,ttl}*
    - continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
    - continue-on-error: true
      name: Check git dirty
      run: 'git status --short

        [ -z "$(git status --short)" ]

        '
    timeout-minutes: 30
name: Strong CI
on:
  repository_dispatch:
    types: trigger-ga___strong_ci.yaml
